### ISSUE TITLE
Issue after inputting API key

### ISSUE THREAD

**Issue by PLBMR** [datadotworld/data.world-py#18]
After inputting the API key after ```dw configure```, I got back this ```python``` error:

```
Traceback (most recent call last):
  File "/usr/local/bin/dw", line 11, in <module>
    load_entry_point('datadotworld==1.0.0b4', 'console_scripts', 'dw')()
  File "/Library/Python/2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/datadotworld/cli.py", line 55, in configure
    config.auth_token = token
  File "/Library/Python/2.7/site-packages/datadotworld/config.py", line 82, in auth_token
    self._config_parser.add_section(self._profile)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 261, in add_section
    raise ValueError, 'Invalid section name: %s' % section
ValueError: Invalid section name: default
```

What should I do about this?

**Comment by rflprr** [comment]
@PLBMR Looks like you found a bug. I'm not able to reproduce it myself, but found documentation that explains how/when it might happen. I should have a fix for it soon. In the mean time, you should be able to use the `-p` option on command line and `profile=` option when invoking library methods and just chose a value different from `default`. I'll ping you again when the fix is live.

**Comment by PLBMR** [comment]
Sounds good. Thank you!

Sincerely,
Michael Rosenberg

**Comment by rflprr** [comment]
@PLBMR Would it be possible for you to upgrade to our latest version and check if it fixes your issue?

**Comment by PLBMR** [comment]
Hey @rflprr , it fixes this issue, but unfortunately I know have a new issue with the ConfigParser. This is discussed in #24 .
