### ISSUE TITLE
New problem with `dw configure`

### ISSUE THREAD

**Issue by PLBMR** [datadotworld/data.world-py#24]
With the new update, I have this issue with after putting my API key into `dw configure`:

```
Traceback (most recent call last):
  File "/usr/local/bin/dw", line 11, in <module>
    load_entry_point('datadotworld==1.0.0b5', 'console_scripts', 'dw')()
  File "/Library/Python/2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/datadotworld/cli.py", line 54, in configure
    config = obj.get('config') or Config(obj['profile'])
  File "/Library/Python/2.7/site-packages/datadotworld/config.py", line 65, in __init__
    self._config_file_path)
  File "/Library/Python/2.7/site-packages/datadotworld/config.py", line 117, in __migrate_config
    config_parser[configparser.DEFAULTSECT] = {'auth_token': token}
  File "/Library/Python/2.7/site-packages/backports/configparser/__init__.py", line 992, in __setitem__
    self.read_dict({key: value})
  File "/Library/Python/2.7/site-packages/backports/configparser/__init__.py", line 760, in read_dict
    self.set(section, key, value)
  File "/Library/Python/2.7/site-packages/backports/configparser/__init__.py", line 1238, in set
    _, option, value = self._validate_value_types(option=option, value=value)
  File "/Library/Python/2.7/site-packages/backports/configparser/__init__.py", line 1221, in _validate_value_types
    raise TypeError("option values must be strings")
TypeError: option values must be strings
```

What should I do about this?

**Comment by rflprr** [comment]
@PLBMR If it's not too much to ask, would you mind sharing with me the output of `pip freeze`. I have a feeling that that will be helpful for me in trying to reproduce the issues you are facing. In the meantime, manually deleting `~/.data.world` should be enough to unblock you.

**Comment by PLBMR** [comment]
Hey @rflprr sure! Sorry I didn't do that earlier. Here's the output to ```pip freeze```:

```
altgraph==0.10.2
appnope==0.1.0
arrow==0.10.0
awscli==1.6.2
backports-abc==0.5
backports.shutil-get-terminal-size==1.0.0
backports.ssl-match-hostname==3.5.0.1
bcdoc==0.12.2
bdist-mpkg==0.5.0
beautifulsoup4==4.5.1
binaryornot==0.4.0
bokeh==0.12.1
bonjour-py==0.3
boto==2.33.0
botocore==0.73.0
bz2file==0.98
cchardet==1.1.3
certifi==2017.1.23
chardet==2.3.0
click==6.7
click-plugins==1.0.3
cligj==0.4.0
colorama==0.2.5
conda==4.1.6
configparser==3.5.0
cookiecutter==1.4.0
datadotworld==1.0.0b5
datapackage==0.8.7
decorator==4.0.11
docutils==0.12
entrypoints==0.2.2
enum34==1.1.6
et-xmlfile==1.0.1
ezodf==0.3.2
feedparser==5.2.1
Fiona==1.7.0.post2
Flask==0.11.1
Flask-Cors==3.0.2
functools32==3.2.3.post2
future==0.16.0
futures==3.0.5
fuzzywuzzy==0.15.0
gensim==0.12.4
genson==0.1.0
gnureadline==6.3.3
GraphLab-Create==2.0.1
GraphLab-Create-License==2.0.1
HeapDict==1.0.0
httplib2==0.9.2
httpretty==0.8.10
ijson==2.3
ipykernel==4.5.1
ipystata==0.3.3
ipython==5.1.0
ipython-genutils==0.2.0
ipywidgets==5.1.4
isodate==0.5.4
itsdangerous==0.24
jdcal==1.3
Jinja2==2.8
jinja2-time==0.2.0
jmespath==0.5.0
joblib==0.10.2
jsonlines==1.1.0
jsonschema==2.6.0
jsontableschema==0.10.0
jsontableschema-pandas==0.3.0
julia==0.1.1
jupyter==1.0.0
jupyter-client==4.4.0
jupyter-console==5.0.0
jupyter-contrib-core==0.3.0
jupyter-contrib-nbextensions==0.2.0
jupyter-core==4.2.0
jupyter-nbextensions-configurator==0.2.2
Keras==1.0.2
linear-tsv==1.0.0
lxml==3.7.3
macholib==1.5.1
MarkupSafe==0.23
matplotlib==1.3.1
metakernel==0.20.1
mistune==0.7.2
modulegraph==0.10.4
mpld3==0.2
multipledispatch==0.4.8
munch==2.0.4
nbconvert==4.2.0
nbformat==4.3.0
networkx==1.11
nltk==3.1
nose==1.3.7
notebook==4.2.3
numpy==1.11.1
oauth2==1.9.0.post1
oauthlib==1.1.2
octave-kernel==0.26.2
olefile==0.44
openpyxl==2.4.5
ox==2.3.804
pandas==0.18.1
pandoc==1.0.0a8
pathlib2==2.1.0
pexpect==4.2.1
pickleshare==0.7.4
Pillow==4.0.0
plotly==2.0.2
pocket==0.3.6
poyo==0.4.0
prettytable==0.7.2
prompt-toolkit==1.0.13
protobuf==3.0.0b2
psclient==2.0
psutil==4.3.1
ptyprocess==0.5.1
py2app==0.7.3
pyasn1==0.1.9
pycosat==0.6.1
pyfiglet==0.7.5
Pygments==2.1.3
pyobjc-core==2.5.1
pyobjc-framework-Accounts==2.5.1
pyobjc-framework-AddressBook==2.5.1
pyobjc-framework-AppleScriptKit==2.5.1
pyobjc-framework-AppleScriptObjC==2.5.1
pyobjc-framework-Automator==2.5.1
pyobjc-framework-CFNetwork==2.5.1
pyobjc-framework-Cocoa==2.5.1
pyobjc-framework-Collaboration==2.5.1
pyobjc-framework-CoreData==2.5.1
pyobjc-framework-CoreLocation==2.5.1
pyobjc-framework-CoreText==2.5.1
pyobjc-framework-DictionaryServices==2.5.1
pyobjc-framework-EventKit==2.5.1
pyobjc-framework-ExceptionHandling==2.5.1
pyobjc-framework-FSEvents==2.5.1
pyobjc-framework-InputMethodKit==2.5.1
pyobjc-framework-InstallerPlugins==2.5.1
pyobjc-framework-InstantMessage==2.5.1
pyobjc-framework-LatentSemanticMapping==2.5.1
pyobjc-framework-LaunchServices==2.5.1
pyobjc-framework-Message==2.5.1
pyobjc-framework-OpenDirectory==2.5.1
pyobjc-framework-PreferencePanes==2.5.1
pyobjc-framework-PubSub==2.5.1
pyobjc-framework-QTKit==2.5.1
pyobjc-framework-Quartz==2.5.1
pyobjc-framework-ScreenSaver==2.5.1
pyobjc-framework-ScriptingBridge==2.5.1
pyobjc-framework-SearchKit==2.5.1
pyobjc-framework-ServiceManagement==2.5.1
pyobjc-framework-Social==2.5.1
pyobjc-framework-SyncServices==2.5.1
pyobjc-framework-SystemConfiguration==2.5.1
pyobjc-framework-WebKit==2.5.1
pyOpenSSL==0.13.1
pyparsing==2.0.1
pyproj==1.9.5.1
pyshp==1.2.3
PySocks==1.6.6
pytesseract==0.1.6
python-dateutil==2.6.0
python-twitter==3.1
pytz==2016.6.1
PyYAML==3.11
pyzmq==16.0.2
qtconsole==4.2.1
rainbowstream==1.3.7
requests==2.13.0
requests-oauthlib==0.6.2
rfc3986==0.4.1
rsa==3.1.2
scikit-learn==0.17.1
scipy==0.17.0
seaborn==0.7.1
sh==1.11
Shapely==1.5.16
sigopt==2.5.0
sigopt-sklearn==1.4.3
simplegeneric==0.8.1
simplejson==3.8.2
singledispatch==3.4.0.3
six==1.10.0
sklearn==0.0
smart-open==1.3.2
snap===3.0.2-dev-macosx10.11.5-x64-py2.7
sseclient==0.0.8
tabulator==0.14.2
tensorflow==0.8.0
terminado==0.6
Theano==0.8.0
tornado==4.4.2
traitlets==4.3.2
tweepy==3.6.0
twitter==1.17.1
unicodecsv==0.14.1
update==0.4.4
urllib3==1.20
wcwidth==0.1.7
Werkzeug==0.11.11
whichcraft==0.4.0
widgetsnbextension==1.2.6
wordcloud==1.3
xattr==0.6.4
xlrd==1.0.0
zope.interface==4.1.1
```

And, that deletion worked. Thank you!
