### ISSUE TITLE
Can't save any unicode in my project

### ISSUE THREAD

**Issue by thesunlover** [datadotworld/data.world-py#97]
Adding a test code:
```
# coding=utf-8
import csv
import datadotworld as dw
DW_USER_NAME = "my_username"
DW_PROJECT_NAME = "my_projectname"
csv_filename = 'test_saving_unicode_strings.csv'
dw_project_path = '{}/{}'.format(DW_USER_NAME, DW_PROJECT_NAME)

with dw.open_remote_file(dw_project_path, csv_filename ) as w:
    csvw = csv.DictWriter(w, fieldnames=['foo', 'bar'])
    csvw.writeheader()
    csvw.writerow({'foo':42, 'bar':u"A"})
    csvw.writerow({'foo':13, 'bar':u"искам уникод запис"})
```
What I have tried:
- adding `encoding="utf-8"` to the open_remove_file call
- encode('utf-8') the 'bad' string
- decode('utf-8') the 'bad' string

Each time I receive UnicodeEncodeError: or UnicodeDecodeError in different place:
```
Traceback (most recent call last):
  File ".\a2.py", line 13, in <module>
    csvw.writerow({'foo':13, 'bar':u"╨╕╤Б╨║╨░╨╝ ╤Г╨╜╨╕╨║╨╛╨┤ ╨╖╨░╨┐╨╕╤Б"})
  File "c:\python27\Lib\csv.py", line 152, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)
```
or
```
Traceback (most recent call last):
  File ".\a2.py", line 13, in <module>
    csvw.writerow({'foo':13, 'bar':u"╨╕╤Б╨║╨░╨╝ ╤Г╨╜╨╕╨║╨╛╨┤ ╨╖╨░╨┐╨╕╤Б".encode("utf-8")})
  File "c:\python27\Lib\csv.py", line 152, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
  File "C:\python27\Lib\site-packages\datadotworld\files.py", line 107, in write
    self._queue.put(value.encode('utf-8'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 3: ordinal not in range(128)
```

**Comment by rflprr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Py: Small bugs](https://trello.com/c/NorfiWKj/43-py-small-bugs)
